services:
  - type: web
    name: expense-manager-backend
    env: docker
    dockerfilePath: ./Dockerfile
    disk:
      name: expense-manager-sqlite-data
      mountPath: /opt/render/project/data
    envVars:
      - key: APP_NAME
        value: Laravel
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/data/database.sqlite
